name: Publish to NPM

on:
  release:
    types: [published]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Extract version from release tag
        id: get_version
        run: |
          # Extract version from GitHub release tag (v1.2.3 -> 1.2.3)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Release version: ${VERSION}"

      - name: Update root package.json version
        run: |
          # Update the version in root package.json
          npm version ${{ steps.get_version.outputs.version }} --no-git-tag-version --allow-same-version

      - name: Sync versions across all packages
        run: pnpm sync-versions

      - name: Publish @feathers-playground/types
        run: |
          cd packages/types
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish feathers-playground
        run: |
          cd packages/core
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Confirm published versions
        run: |
          echo "✅ Successfully published packages:"
          echo "- feathers-playground@${{ steps.get_version.outputs.version }}"
          echo "- @feathers-playground/types@${{ steps.get_version.outputs.version }}"
